### PR TITLE
Allow dashboard with multiple queries for same target

### PR DESCRIPTION
**Pull request by mihanuta**
This is done by adding filtering by RefID for QueryRequest

### CODE REVIEW

**Comment by clambin** [comment]
LGTM, but please add/adapt a unit test to validate the behaviour.

**Comment by mihanuta** [comment]
I included a test case where a request contains multiple target queries, each represented individually by a pair of {target name, refID}. Each response is based on the provided payload

**Review by clambin — APPROVED** [review]

**Comment by clambin** [comment]
Thanks!  Very elegant. :)   Merged and will push out v0.7.1.

**Comment by mihanuta** [comment]
Thank you also!

**Pull request merged**
